### ISSUE TITLE
The desktop file configuration is only for Doomseeker

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/com.zandronum.Zandronum#8]
Zandronum has capabilities to run offline. It has its own independent gui to run games separately. It should be 2 desktop files and not just one.

**Comment by Eonfge** [comment]
@EchedeyLR I'm sorry for missing your comment, I was not actively watching the issues. Appearently, becoming a maintainer does not make you auto notify.

On the topic of playing Zandronum locally. I've added the server component so it is easier to create and run local games. 

The actual singleplayer mode, can also be started from Doomseeker. This adds the aditional benefit of being able to configure your own mods and such. 

Otherwise, you'll be forced to use the command line.

```
$ flatpak run --command="zandronum -file doom.wad mod.pk3" com.zandronum.Zandronum
```

I feel that as of now, there are enough easy to use UI options to start Zandronum, so I'm not sure if adding a second icon just for a limited setup of singleplayer games is worthwhile.

**Comment by EchedeyLR** [comment]
> The actual singleplayer mode, can also be started from Doomseeker.

Could you show me how?. 

Also, even being that the case, the software is running is Zandronum + Doomseeker not just Zandronum that is just a client+engine software that is provided alone but which you can use with Doomseeker.

**Comment by Eonfge** [comment]
> Could you show me how?.

File -> Create game > mode -> [x] Play offline

And Zandronum and Doomseeker are normally bundled. You can indeed start Zandronum manually, but it serves little purpose if you ask me.

If you wish to play a lot of singleplayer games and you're not scared of the Command line, I will actually recommend GZdoom over Zandronum, they share much code but GZDoom is better maintained:
https://flathub.org/apps/details/org.zdoom.GZDoom

**Comment by Eonfge** [comment]
I've updated the README, let me know if you miss something:
https://github.com/flathub/com.zandronum.Zandronum/blob/master/README.md

**Comment by EchedeyLR** [comment]
Well, for now it seems doesn't clarify which I mentioned before. It is different software and even using the "bundled installer" both software are different and separated. The name and the readme should clarify that.

**Comment by EchedeyLR** [comment]
Thank you for the trick too.

**Comment by Eonfge** [comment]
Not sure if there is any follow-up on this issue. I'll close it for now.
